"""empty message

Revision ID: 587744c77c87
Revises: e8b00f2a6827
Create Date: 2018-04-19 11:41:39.257845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587744c77c87'
down_revision = 'e8b00f2a6827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
